// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1kujqc5Ym0J7a3_OT-UDUgcBi-vlHxA8',
    appId: '1:67999091410:web:a4a14c3428712fc614bb0b',
    messagingSenderId: '67999091410',
    projectId: 'disenyplus-a1af8',
    authDomain: 'disenyplus-a1af8.firebaseapp.com',
    storageBucket: 'disenyplus-a1af8.appspot.com',
    measurementId: 'G-QMCDKB0128',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy09q5I0SVdvcOf9IOhsv1zKIr0l6e1gY',
    appId: '1:67999091410:android:a49c8ce49bb834e714bb0b',
    messagingSenderId: '67999091410',
    projectId: 'disenyplus-a1af8',
    storageBucket: 'disenyplus-a1af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGpfAJuzHrg9RvlUC3-oljwwZv5LqZXyc',
    appId: '1:67999091410:ios:c9d619f210c93d3814bb0b',
    messagingSenderId: '67999091410',
    projectId: 'disenyplus-a1af8',
    storageBucket: 'disenyplus-a1af8.appspot.com',
    iosBundleId: 'com.example.disneyplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGpfAJuzHrg9RvlUC3-oljwwZv5LqZXyc',
    appId: '1:67999091410:ios:72bfe3076090fc4814bb0b',
    messagingSenderId: '67999091410',
    projectId: 'disenyplus-a1af8',
    storageBucket: 'disenyplus-a1af8.appspot.com',
    iosBundleId: 'com.example.disneyplus.RunnerTests',
  );
}
